tigerdata:
  enabled: true

  image:
    repository: timescale/timescaledb
    tag: 2.14.2-pg16
    pullPolicy: IfNotPresent

  auth:
    username: postgres
    password: tigerdata
    database: timescaledb

  storage:
    size: 5Gi

  service:
    type: ClusterIP
    port: 5432  # PostgreSQL port

  nodePort:
    enabled: true
    port: 31432
