{{- if .Values.questdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: questdb
spec:
  selector:
    app: questdb
  type: {{ .Values.questdb.service.type }}
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: pgwire
      port: 8812
      targetPort: 8812
    - name: ilp
      port: 9009
      targetPort: 9009
{{- end }}
