{{- if and .Values.mssql.enabled .Values.mssql.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  SA_PASSWORD: {{ .Values.mssql.auth.saPassword | b64enc }}
{{- end }}
