{{- if .Values.mssql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mssql-nodeport
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: {{ .Values.mssql.service.nodePort }}
  selector:
    app: mssql
{{- end }}
