{{- if .Values.mssql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: mssql
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsGroup: 10001
        runAsNonRoot: true
      restartPolicy: Always
      containers:
        - name: mssql
          image: "{{ .Values.mssql.image.repository }}:{{ .Values.mssql.image.tag }}"
          imagePullPolicy: {{ .Values.mssql.image.pullPolicy }}
          ports:
            - containerPort: 1433
              name: mssql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
            - name: MSSQL_DATA_DIR
              value: /var/opt/mssql/data
            - name: MSSQL_LOG_DIR
              value: /var/opt/mssql/log
            - name: MSSQL_BACKUP_DIR
              value: /var/opt/mssql/backup
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
  volumeClaimTemplates:
    - metadata:
        name: mssql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mssql.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.mssql.storage.size }}
{{- end }}