milvus:
  enabled: true
  image:
    repository: milvusdb/milvus
    tag: v2.3.9
    pullPolicy: IfNotPresent

  replicas: 1

  service:
    port: 19530
    nodePort: 31953

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  secret:
    enabled: true
    name: milvus-secret
    data:
      username: milvus
      password: milvus123
