milvus:
  enabled: true
  image:
    repository: milvusdb/milvus
    tag: v2.3.3
    pullPolicy: IfNotPresent
  storage:
    size: 10Gi
  config:
    etcd:
      endpoints: "milvus-etcd:2379"
    minio:
      endpoint: "milvus-minio:9000"
      accessKey: "minioadmin"
      secretKey: "minioadmin"
      bucket: "milvus"
      secure: false
    pulsar:
      endpoint: "milvus-pulsar:6650"
  service:
    type: ClusterIP
    ports:
      grpc: 19530
      http: 9091
      metrics: 9090
    nodePort:
      enabled: true
      ports:
        grpc: 30001
        http: 30002
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "8Gi"