milvus:
  enabled: true
  image:
    repository: zilliz/milvus
    tag: 2.0.0-rc8-20211104-d7f4106
    pullPolicy: IfNotPresent

  replicas: 1

  service:
    port: 19530
    nodePort: 31953

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  secret:
    enabled: true
    name: milvus-secret
    data:
      username: milvus
      password: milvus123
