{{- if .Values.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  hostPath:
    path: {{ .Values.storage.path }}
{{- end }}
