{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: mongodb
{{- end }}    
