{{- if .Values.typesense.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: typesense-secret
type: Opaque
stringData:
  TYPESENSE_API_KEY: {{ .Values.typesense.auth.apiKey | quote }}
{{- end }}
