{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.password | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.auth.database | quote }}
{{- end }}