{{- if .Values.neo4j.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
type: Opaque
stringData:
  NEO4J_AUTH: "{{ .Values.neo4j.auth.username }}/{{ .Values.neo4j.auth.password }}"
{{- end }}
