{{- if .Values.neo4j.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - port: 7687  
      targetPort: 7687
      name: bolt
    - port: 7474
      targetPort: 7474
      name: http
{{- end }}
