{{- if .Values.dragonfly.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dragonfly
spec:
  type: ClusterIP
  selector:
    app: dragonfly
  ports:
    - port: 6379
      targetPort: 6379
      name: dragonfly
{{- end }}
