{{- if .Values.dragonfly.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-nodeport
spec:
  type: NodePort
  selector:
    app: dragonfly
  ports:
    - name: dragonfly
      port: 6379
      targetPort: 6379
      nodePort: {{ .Values.dragonfly.service.nodePort }}
{{- end }}
