{{- if .Values.meilisearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-secret
type: Opaque
stringData:
  MEILI_MASTER_KEY: {{ .Values.meilisearch.auth.masterKey | quote }}
{{- end }}
