{{- if .Values.meilisearch.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meilisearch
  labels:
    app: meilisearch
spec:
  serviceName: meilisearch
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: "{{ .Values.meilisearch.image.repository }}:{{ .Values.meilisearch.image.tag }}"
          imagePullPolicy: {{ .Values.meilisearch.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.meilisearch.service.port }}
              name: http
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret
                  key: MEILI_MASTER_KEY
          volumeMounts:
            - name: meilisearch-data
              mountPath: /meili_data
  volumeClaimTemplates:
    - metadata:
        name: meilisearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.meilisearch.storage.size }}
{{- end }}
