apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jaas-config
  namespace: k
data:
  jaas.conf: |
    KafkaServer {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="${KAFKA_USERNAME}"
      password="${KAFKA_PASSWORD}"
      user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";
    };
