{{- if .Values.strimzi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: strimzi-secret
type: Opaque
stringData:
  KAFKA_USERNAME: {{ .Values.strimzi.auth.username | quote }}
  KAFKA_PASSWORD: {{ .Values.strimzi.auth.password | quote }}
{{- end }}
