{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
stringData:
  KAFKA_USERNAME: {{ .Values.kafka.auth.username | quote }}
  KAFKA_PASSWORD: {{ .Values.kafka.auth.password | quote }}
{{- end }}
