{{- if and .Values.kafka.enabled .Values.kafka.nodePortService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
spec:
  selector:
    app: kafka
  type: NodePort
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      nodePort: {{ .Values.kafka.nodePortService.ports.kafka }}
{{- end }}
