{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
{{- end }}
