{{- if .Values.tigerdata.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tigerdata-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.tigerdata.auth.username }}"
  POSTGRES_PASSWORD: "{{ .Values.tigerdata.auth.password }}"
  POSTGRES_DB: "{{ .Values.tigerdata.auth.database }}"
{{- end }}
