{{- if and .Values.tigerdata.enabled .Values.tigerdata.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tigerdata-nodeport
  labels:
    app: tigerdata
spec:
  type: NodePort
  selector:
    app: tigerdata
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ .Values.tigerdata.nodePort.port }}
      name: pg
{{- end }}
