apiVersion: v1
kind: Secret
metadata:
  name: pinot-secret
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.pinot.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- if not .Values.secrets.pinot.data }}
  # Default empty secret
  placeholder: {{ "dev-mode" | b64enc }}
  {{- end }}