{{- if and .Values.pinot.enabled .Values.pinot.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pinot-secret
type: Opaque
stringData:
  CONTROLLER_USER: {{ .Values.pinot.auth.username | quote }}
  CONTROLLER_PASSWORD: {{ .Values.pinot.auth.password | quote }}
{{- end }}
