{{- if .Values.pinot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pinot
spec:
  selector:
    app: pinot
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: controller
  type: ClusterIP
{{- end }}
