{{- if .Values.pinot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pinot-nodeport
spec:
  selector:
    app: pinot
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: {{ .Values.pinot.controller.nodePort }}
      protocol: TCP
      name: controller
  type: NodePort
{{- end }}
