{{- if .Values.pinot.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pinot
  labels:
    app: pinot
spec:
  serviceName: pinot-headless
  replicas: 1
  selector:
    matchLabels:
      app: pinot
  template:
    metadata:
      labels:
        app: pinot
    spec:
      containers:
        - name: pinot
          image: "{{ .Values.pinot.image.repository }}:{{ .Values.pinot.image.tag }}"
          imagePullPolicy: "{{ .Values.pinot.image.pullPolicy }}"
          command:
            - "/opt/pinot/bin/pinot-admin.sh"
          args:
            - "StartController"
          ports:
            - containerPort: {{ .Values.pinot.controller.port }}
              name: controller
          volumeMounts:
            - name: pinot-data
              mountPath: /var/pinot
          env:
            - name: MY_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAVA_OPTS
              value: "-Xms512M -Xmx1G"
            - name: PINOT_COMPONENT
              value: "Controller"
            - name: CLUSTER_NAME
              value: "pinot-cluster"
            - name: CONFIG_ALLOW_ZKLESS
              value: true
            - name: CONTROLLER_MODE
              value: "helix-less"
            - name: CONTROLLER_PORT
              value: "{{ .Values.pinot.controller.port | quote }}"
            - name: CONTROLLER_HOST
              value: "$(MY_NODE_IP)"
            - name: CONTROLLER_USER
              valueFrom:
                secretKeyRef:
                  name: pinot-secret
                  key: CONTROLLER_USER
            - name: CONTROLLER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pinot-secret
                  key: CONTROLLER_PASSWORD

  volumeClaimTemplates:
    - metadata:
        name: pinot-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.pinot.storage.size }}
{{- end }}
