{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysql.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.storage.className }}
  hostPath:
    path: {{ .Values.mysql.storage.path }}
{{- end }}