{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | b64enc | quote }}
{{- end }}
