{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: {{ .Values.mysql.service.nodePort }}
  selector:
    app: mysql
{{- end }}