{{- if .Values.arangodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: arangodb-secret
type: Opaque
stringData:
  ARANGO_ROOT_PASSWORD: {{ .Values.arangodb.root.password | quote }}
{{- end }}
