{{- if .Values.arangodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: arangodb-nodeport
spec:
  selector:
    app: arangodb
  ports:
    - port: 8529
      targetPort: 8529
      nodePort: {{ .Values.arangodb.service.nodePort }}
      protocol: TCP
  type: NodePort
{{- end }}
