{{- if .Values.cassandra.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-secret
type: Opaque
stringData:
  CASSANDRA_PASSWORD: {{ .Values.cassandra.auth.password | quote }}
{{- end }}
