{{- if .Values.cassandra.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  type: ClusterIP
  ports:
    - name: cql
      port: 9042
      targetPort: 9042
    - name: intra
      port: 7000
      targetPort: 7000
    - name: jmx
      port: 7199
      targetPort: 7199
{{- end }}
