{{- if .Values.oracle.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
type: Opaque
stringData:
  ORACLE_PASSWORD: {{ .Values.oracle.credentials.sysPassword }}
  APP_USER: {{ .Values.oracle.credentials.appUser }}
  APP_USER_PASSWORD: {{ .Values.oracle.credentials.appUserPassword }}
{{- end }}
