{{- if .Values.oracle.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: oracle
spec:
  type: ClusterIP
  selector:
    app: oracle
  ports:
    - port: 1521
      targetPort: 1521
      name: oracle
{{- end }}
