{{- if .Values.oracle.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: oracle-nodeport
spec:
  type: NodePort
  selector:
    app: oracle
  ports:
    - port: 1521
      targetPort: 1521
      nodePort: {{ .Values.oracle.service.nodePort }}
      protocol: TCP
      name: oracle
{{- end }}
