# Simple Apache Pinot Configuration for Development
pinot:
  enabled: true
  image:
    repository: apachepinot/pinot
    tag: "0.12.1"
    pullPolicy: IfNotPresent
  
  # Single process mode (Helix Mode) - includes all components
  replicas: 1

  
  storage:
    size: "10Gi"


# Service Configuration
service:
  type: ClusterIP
  port: 9000

# NodePort Service Configuration
nodePort:
  enabled: true
  port: 30090

# Secrets
secrets:
  pinot:
    data: {}