mongodb:
  enabled: true
  replicaCount: 1

  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent

  storage:
    size: 5Gi
    className: manual
    path: /data/mongodb

  auth:
    enabled: true
    username: admin
    password: secret
    database: admin

  service:
    nodePort: 32017