mssql:
  enabled: true
  name: mssql
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: 2019-latest
    pullPolicy: IfNotPresent

  storage:
    size: 5Gi
    path:  /data/mssql

  credentials:
    saPassword: "SuperSecret@123"

  service:
    nodePort: 31433

  # See https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15
  edition: Developer

