{{- if .Values.weaviate.enabled }}
{{- if .Values.weaviate.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.weaviate.secret.name }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.weaviate.secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
