{{- if .Values.weaviate.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: weaviate
spec:
  type: ClusterIP
  selector:
    app: weaviate
  ports:
    - port: {{ .Values.weaviate.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
{{- end }}
