questdb:
  enabled: true

  image:
    repository: questdb/questdb
    tag: latest
    pullPolicy: IfNotPresent

  service:
    port: 9000
    type: ClusterIP

  nodePortService:
    enabled: true
    nodePort: 30900

  storage:
    size: 5Gi
