{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
type: Opaque
stringData:
  ELASTIC_USERNAME: {{ .Values.elasticsearch.auth.username }}
  ELASTIC_PASSWORD: {{ .Values.elasticsearch.auth.password }}
{{- end }}
