{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: elasticsearch
{{- end }}    
