{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.credentials.rootPassword }}
  MARIADB_DATABASE: {{ .Values.mariadb.credentials.database }}
{{- end }}