{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mariadb-nodeport
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: {{ .Values.mariadb.service.nodePort }}
  selector:
    app: mariadb
{{- end }}