{{- if .Values.milvus.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: milvus-secret
type: Opaque
data:
  minioAccessKey: {{ .Values.milvus.config.minio.accessKey | b64enc | quote }}
  minioSecretKey: {{ .Values.milvus.config.minio.secretKey | b64enc | quote }}
{{- end }}