{{- if .Values.milvus.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.milvus.secret.name }}
type: Opaque
data:
  username: {{ .Values.milvus.secret.data.username | b64enc }}
  password: {{ .Values.milvus.secret.data.password | b64enc }}
{{- end }}
