{{- if .Values.milvus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: milvus
  labels:
    app: milvus
spec:
  type: {{ .Values.milvus.service.type }}
  ports:
    - port: {{ .Values.milvus.service.ports.grpc }}
      targetPort: grpc
      name: grpc
    - port: {{ .Values.milvus.service.ports.http }}
      targetPort: http
      name: http
    - port: {{ .Values.milvus.service.ports.metrics }}
      targetPort: metrics
      name: metrics
  selector:
    app: milvus
{{- end }}