{{- if and .Values.milvus.enabled .Values.milvus.service.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: milvus-nodeport
  labels:
    app: milvus
spec:
  type: NodePort
  ports:
    - port: {{ .Values.milvus.service.ports.grpc }}
      targetPort: grpc
      nodePort: {{ .Values.milvus.service.nodePort.ports.grpc }}
      name: grpc
    - port: {{ .Values.milvus.service.ports.http }}
      targetPort: http
      nodePort: {{ .Values.milvus.service.nodePort.ports.http }}
      name: http
  selector:
    app: milvus
{{- end }}