apiVersion: v1
kind: Service
metadata:
  name: milvus
  labels:
    app: milvus
spec:
  type: ClusterIP
  ports:
    - port: 19530
      targetPort: milvus
      protocol: TCP
      name: milvus
  selector:
    app: milvus
