{{- if .Values.milvus.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus
  labels:
    app: milvus
spec:
  serviceName: milvus
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          image: "{{ .Values.milvus.image.repository }}:{{ .Values.milvus.image.tag }}"
          imagePullPolicy: {{ .Values.milvus.image.pullPolicy }}
          command: ["/tini", "--"]
          args:
            - "/milvus-run.sh"
            - "standalone"
          ports:
            - containerPort: {{ .Values.milvus.service.ports.grpc }}
              name: grpc
            - containerPort: {{ .Values.milvus.service.ports.http }}
              name: http
            - containerPort: {{ .Values.milvus.service.ports.metrics }}
              name: metrics
          env:
            - name: ETCD_ENDPOINTS
              value: {{ .Values.milvus.config.etcd.endpoints | quote }}
            - name: MINIO_ENDPOINT
              value: {{ .Values.milvus.config.minio.endpoint | quote }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: milvus-secret
                  key: minioAccessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: milvus-secret
                  key: minioSecretKey
            - name: MINIO_BUCKET_NAME
              value: {{ .Values.milvus.config.minio.bucket | quote }}
            - name: MINIO_USE_SSL
              value: {{ .Values.milvus.config.minio.secure | quote }}
            - name: PULSAR_ENDPOINT
              value: {{ .Values.milvus.config.pulsar.endpoint | quote }}
          volumeMounts:
            - name: milvus-data
              mountPath: /var/lib/milvus
          resources:
            {{- toYaml .Values.milvus.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: milvus-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.milvus.storage.size }}
{{- end }}