apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: milvus
  labels:
    app: milvus
spec:
  replicas: {{ .Values.milvus.replicas }}
  selector:
    matchLabels:
      app: milvus
  serviceName: milvus-headless
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          image: "{{ .Values.milvus.image.repository }}:{{ .Values.milvus.image.tag }}"
          imagePullPolicy: {{ .Values.milvus.image.pullPolicy }}
          command: ["/milvus/tools/run.sh"]
          args: ["milvus", "standalone"]
          ports:
            - containerPort: 19530
              name: milvus
          env:
            - name: MILVUS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.milvus.secret.name }}
                  key: username
            - name: MILVUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.milvus.secret.name }}
                  key: password
          volumeMounts:
            - name: milvus-storage
              mountPath: /var/lib/milvus
  volumeClaimTemplates:
    - metadata:
        name: milvus-storage
      spec:
        accessModes: {{ .Values.milvus.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.milvus.persistence.size }}
