cassandra:
  enabled: true

  image:
    repository: cassandra
    tag: 4.1.4
    pullPolicy: IfNotPresent

  service:
    ports:
      cql: 9042
      intraNode: 7000
      jmx: 7199
    type: ClusterIP

  nodePortService:
    enabled: true
    ports:
      cql: 32042

  auth:
    username: cassandra
    password: cassandra  # Set your own secure password here

  storage:
    size: 10Gi

  cluster:
    name: batcave
    datacenter: dc1
    rack: rack1
