{{- if .Values.cockroachdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cockroachdb-secret
type: Opaque
stringData:
  COCKROACH_USER: "{{ .Values.cockroachdb.auth.username }}"
  COCKROACH_PASSWORD: "{{ .Values.cockroachdb.auth.password }}"
{{- end }}
