{{- if and .Values.cockroachdb.enabled .Values.cockroachdb.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-nodeport
  labels:
    app: cockroachdb
spec:
  type: NodePort
  selector:
    app: cockroachdb
  ports:
    - name: sql
      port: 26257
      targetPort: 26257
      nodePort: {{ .Values.cockroachdb.nodePort.sql }}
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.cockroachdb.nodePort.http }}
{{- end }}
