kafka:
  enabled: true

  image:
    repository: bitnami/kafka
    tag: 3.6.1
    pullPolicy: IfNotPresent

  broker:
    replicas: 1
    storage:
      size: 10Gi

  service:
    kafkaPort: 9092
    internalPort: 9093
    type: ClusterIP

  nodePortService:
    enabled: true
    ports:
      kafka: 31092

  auth:
    username: admin
    password: adminpass
