{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
stringData:
  CLICKHOUSE_PASSWORD: "{{ .Values.clickhouse.auth.password }}"
{{- end }}
