{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - port: 9000
      targetPort: 9000
      name: tcp
    - port: 8123
      targetPort: 8123
      name: http
{{- end }}
