{{- if and .Values.clickhouse.enabled .Values.clickhouse.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-nodeport
  labels:
    app: clickhouse
spec:
  type: NodePort
  selector:
    app: clickhouse
  ports:
    - name: tcp
      port: 9000
      targetPort: 9000
      nodePort: {{ .Values.clickhouse.nodePort.tcp }}
    - name: http
      port: 8123
      targetPort: 8123
      nodePort: {{ .Values.clickhouse.nodePort.http }}
{{- end }}
