{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_USERNAME: "{{ .Values.influxdb.auth.username }}"
  DOCKER_INFLUXDB_INIT_PASSWORD: "{{ .Values.influxdb.auth.password }}"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ .Values.influxdb.auth.token }}"
  DOCKER_INFLUXDB_INIT_ORG: "{{ .Values.influxdb.auth.org }}"
  DOCKER_INFLUXDB_INIT_BUCKET: "{{ .Values.influxdb.auth.bucket }}"
{{- end }}
