{{- if and .Values.influxdb.enabled .Values.influxdb.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: influxdb-nodeport
  labels:
    app: influxdb
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: {{ .Values.influxdb.nodePort.port }}
      name: api
{{- end }}
