{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
      name: api
{{- end }}
