{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8086
      name: api
  selector:
    app: influxdb
{{- end }}
